# Generated by Django 4.1.1 on 2024-02-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0003_rename_book_bookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='bookdes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
