# Generated by Django 4.1.1 on 2024-02-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0004_bookmodel_bookdes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='bookdes',
            field=models.TextField(null=True),
        ),
    ]
