# Generated by Django 4.1.1 on 2024-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0005_alter_bookmodel_bookdes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
