# Generated by Django 4.1.1 on 2024-02-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0007_writereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='bookprice',
            field=models.IntegerField(null=True),
        ),
    ]
