# Generated by Django 4.1.1 on 2024-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0009_bookmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writereview',
            name='review_des',
            field=models.TextField(null=True),
        ),
    ]
