# Generated by Django 4.1.1 on 2024-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0010_alter_writereview_review_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writereview',
            name='review_des',
            field=models.TextField(),
        ),
    ]
