# Generated by Django 4.1.1 on 2024-02-22 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0011_alter_writereview_review_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='writereview',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeui.usermodel'),
        ),
    ]
