# Generated by Django 4.1.1 on 2024-02-22 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0012_writereview_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writereview',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeui.usermodel'),
        ),
    ]
