# Generated by Django 4.1.1 on 2024-02-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0013_alter_writereview_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
