# Generated by Django 4.1.1 on 2024-02-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeui', '0015_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
